[target.aarch64-unknown-linux-gnu]
pre-build = [
  "dpkg --add-architecture $CROSS_DEB_ARCH",
  "apt-get update && apt-get install --assume-yes libssl-dev:$CROSS_DEB_ARCH"
]

[target.aarch64-linux-android]
image = "ghcr.io/cross-rs/aarch64-linux-android:main"

[target.armv7-linux-androideabi]
image = "ghcr.io/cross-rs/armv7-linux-androideabi:main"

[target.aarch64-unknown-linux-musl]
pre-build = [
  "apt-get update && apt-get install --assume-yes musl-tools"
]
